run:
	gcc -c chef_named.c -Wall -lrt -lpthread 
	gcc chef_named.o -o ch -lrt -lpthread 
	gcc -c pushers_named.c -Wall -lrt -lpthread 
	gcc pushers_named.o -o push -lrt -lpthread 
	gcc wholesaler_named.c -c -Wall -lrt -lpthread
	gcc wholesaler_named.o -o hw3named -lrt -lpthread
	gcc -c chef_unnamed.c -Wall -lrt -lpthread 
	gcc chef_unnamed.o -o ch1 -lrt -lpthread 
	gcc -c pushers_unnamed.c -Wall -lrt -lpthread 
	gcc pushers_unnamed.o -o push1 -lrt -lpthread 
	gcc wholesaler_unnamed.c -c -Wall -lrt -lpthread
	gcc wholesaler_unnamed.o -o hw3unnamed -lrt -lpthread
